# Generated by Django 2.1.15 on 2021-02-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210226_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.PositiveIntegerField(default=10000, verbose_name='Current balance'),
        ),
    ]
