# Generated by Django 2.1.15 on 2021-02-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210226_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant_id',
            field=models.IntegerField(max_length=4),
        ),
    ]
