# Generated by Django 2.1.15 on 2021-02-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210226_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='Current balance'),
        ),
    ]
